// Created by lin on 2023/9/11.
#ifndef INC_10_BUILD_DEMO10_STATIC_INCLUDE_SUB_H_
#define INC_10_BUILD_DEMO10_STATIC_INCLUDE_SUB_H_

int sub(int x, int y);

#endif //INC_10_BUILD_DEMO10_STATIC_INCLUDE_SUB_H_
